---
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'po/**'
      - 'data/**'
    
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-22.04
    container: debian:bookworm-slim
    permissions:
      contents: write  
    steps:
      - name: Install checkout dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git \
          ca-certificates rsync openssh-client
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./ide/provisioning/install-debian-packages.sh UPDATE
          ./ide/provisioning/install-debian-packages.sh BASE
      - name: make working directory a safe commit dir
        run: git config --global --add safe.directory /__w/XCSoar/XCSoar

      - name: Backup existing files in temp
        run: |
          mkdir -v -p ./temp
          cp -v -r ./po/xcsoar.pot ./temp 
          mv -v -T ./temp/xcsoar.pot ./temp/xcsoar0.po # old file as backup
          cp -v -r ./po/xcsoar.pot ./temp
          mv -v -T ./temp/xcsoar.pot ./temp/xcsoar1.po # old file to compare
                    
      - name: Update pot files
        run: make update-po
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autocommit translation sources"
          file_pattern: "*.pot"
          
      - name: copy new pot file
        run: |
          cp -v ./po/xcsoar.pot ./temp # new file to compare
          mv -v -T ./temp/xcsoar.pot ./temp/xcsoar2.po
      - name: remove timestamps
        run: |
          sed -i '/^"POT-Creation-Date:/d' ./temp/xcsoar1.po # old file
          sed -i '/^"POT-Creation-Date:/d' ./temp/xcsoar2.po # new file

      - name: Check for differences
        run: |
          if diff -q ./temp/xcsoar1.po ./temp/xcsoar2.po; then
            echo "No difference found, restore backup file"
            mv -v -T ./temp/xcsoar0.po ./po/xcsoar.pot # move backup files back to po-dir
          else
            echo "Differences found, keep new files"
          fi

        


