---
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'po/**'
      - 'data/**'
    
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-22.04
    container: debian:bookworm-slim
    permissions:
      contents: write  
    steps:
      - name: Install checkout dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git \
          ca-certificates rsync openssh-client
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./ide/provisioning/install-debian-packages.sh UPDATE
          ./ide/provisioning/install-debian-packages.sh BASE
      - name: make working directory a safe commit dir
        run: git config --global --add safe.directory /__w/XCSoar/XCSoar

      - name: Backup existing files in temp
        run: |
          mkdir -p temp
          cp -v -r po/xcsoar.pot temp # später um *.po erweitern
          cp -v po/xcsoar.pot temp/xcsoar.pot1 # old file to compare
          
      - name: Update pot files
        run: make update-po
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autocommit translation sources"
          file_pattern: "*.pot"
          
      - name: copy new pot file
        run: cp -v po/xcsoar.pot temp/xcsoar.pot2 # new file to compare
      - name: remove timestamps
        run: |
          sed -i '/^"POT-Creation-Date:/d' temp/xcsoar.pot1 # old file
          sed -i '/^"POT-Creation-Date:/d' temp/xcsoar.pot2 # new file
        


