---
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'po/**'
      - 'data/**'
    
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-22.04
    container: debian:bookworm-slim
    permissions:
      contents: write  
    steps:
      - name: Install checkout dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git \
          ca-certificates rsync openssh-client
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./ide/provisioning/install-debian-packages.sh UPDATE
          ./ide/provisioning/install-debian-packages.sh BASE
      - name: make working directory a safe commit dir
        run: git config --global --add safe.directory /__w/XCSoar/XCSoar

      - name: Backup existing files
        run: |
          mkdir temp
          cp -v -r po/*.* temp

