---
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'po/**'
      - 'data/**'
    
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-22.04
    container: debian:bookworm-slim
    permissions:
      contents: write  
    steps:
      - name: Install checkout dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git \
          ca-certificates rsync openssh-client
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./ide/provisioning/install-debian-packages.sh UPDAT
          ./ide/provisioning/install-debian-packages.sh BASE
      - name: make working directory a safe commit dir
        run: git config --global --add safe.directory /__w/XCSoar/XCSoar

      - name: copy existing file in tempo/
        run: |
          mkdir -v -p ./tempo/
          cp -v po/xcsoar.pot tempo/xcsoar.px1 # old file to test
          cp -v po/xcsoar.pot tempo/xcsoar.pox # file to update
          cp -v po/xcsoar.pot tempo/xcsoar.pot # original for comparison
                 
      - name: Update pot files
        run: make update-po
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autocommit translation sources"
          file_pattern: "*.pox" # update only the test file
          
      - name: remove timestamps
        run: |
          sed -i '/^"POT-Creation-Date:/d' tempo/xcsoar.px1 # old file
          sed -i '/^"POT-Creation-Date:/d' tempo/xcsoar.pox # new file
      - name: Check for differences
        run: |
          if diff -q tempo/xcsoar.px1 tempo/xcsoar.pox; then
            echo "No difference found, no updates in ./po needed"
          else
            echo "Differences found, run real update-po"
            - name: Update pot files
              run: make update-po
            - name: Push Local Changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "Autocommit translation sources"
                file_pattern: "*.pot" # update real files
          fi
      - name: Clean-up
        run: |
          cd tempo/
          ls -l
            
