---
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'po/**'
      - 'data/**'
    
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-22.04
    container: debian:bookworm-slim
    permissions:
      contents: write  
    steps:
      - name: Install checkout dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git \
          ca-certificates rsync openssh-client
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./ide/provisioning/install-debian-packages.sh UPDAT
          ./ide/provisioning/install-debian-packages.sh BASE
      - name: make working directory a safe commit dir
        run: git config --global --add safe.directory /__w/XCSoar/XCSoar

      - name: test for timestamp
        run: |
          cd ./po/
          ls -l xcsoar*.* # to verify presence of files
          cp -v po/xcsoar.pot po/xcsoar_backup.px0 # original as backup
          cd ./po/
          ls -l xcsoar*.* # to verify presence of files
          exit 0

      - name: duplicate existing file in po/ and remove timestamp of ref-file
        run: |
          cp -v po/xcsoar.pot po/xcsoar_backup.px0 # original as backup
          cp -v po/xcsoar.pot po/xcsoar_reference.px1 # old file as reference
          cp -v po/xcsoar.pot po/xcsoar_test.pot # file to update for test with timestamp
          sed -i '/^"POT-Creation-Date:/d' po/xcsoar_reference.px1 # ref file without timestamp
          cd ./po/
          ls -l xcsoar*.* # to verify presence of files
          
      - name: Update pot file
        run: make update-po
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autocommit test files" # xcsoar.pot and xcsoar_test.pot
          file_pattern: "*.pot"
          
      - name: Show size of updated files
        run: |
          cd ./po/
          ls -l xcsoar*.* # to verify presence and size of files
          
      - name: remove timestamp of updated test file
        run: |
          cp -v po/xcsoar.pot po/xcsoar_test.pot
          sed -i '/^"POT-Creation-Date:/d' po/xcsoar_test.pot # updated file
          cd ./po/
          ls -l xcsoar*.* # to verify presence and size of files
      - name: Check for differences
        run: |
          if diff --normal po/xcsoar_test.pot po/xcsoar_reference.px1; then
            echo "No difference found, restore original pot file"
            rm -v po/xcsoar.pot
            mv -v po/xcsoar_backup.px0 po/xcsoar.pot # use backup pot file
          else
            echo "Differences found, keep updated xcsoar.pot" 
          fi
                    
      - name: Clean-up
        run: |
          cd ./po/
          ls -l xcsoar*.* # to verify presence of files
          # rm -v po/xcsoar_test.pot
          # rm -v po/xcsoar_reference.px1
            
