---
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'po/**'
      - 'data/**'
    permissions:
      contents: write

jobs:
  autocommit-pot-files:
    runs-on: ubuntu-22.04
    container: debian:bookworm-slim
    steps:
      - name: Install checkout dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git \
          ca-certificates rsync openssh-client
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./ide/provisioning/install-debian-packages.sh UPDATE
          ./ide/provisioning/install-debian-packages.sh BASE
      - name: make working directory a safe commit dir
        run: git config --global --add safe.directory /__w/XCSoar/XCSoar
      - name: Create files for check
        run: |
          cp po/xcsoar.pot po/xcsoar.pot0 # backup of old pot-file
          cp po/xcsoar.pot po/xcsoar.pox # file to compare with new pot-file
      - name: Update pot file for check
        run: make update-po
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autocommit xcsoar.pot for test"
          file_pattern: "*.pot" # update and push pot
      - name: Remove timestamps
        run: |
          sed -i '/^"POT-Creation-Date:/d' po/xcsoar.pox # old file
          sed -i '/^"POT-Creation-Date:/d' po/xcsoar.pot # new file
      - name: Compare new file with old file
        run: |
          if diff -q po/xcsoar.pot po/xcsoar.pox; then
            echo "No difference found, restore backup file"
            rm po/xcsoar.pot # modified file without timestamp
            mv po/xcsoar.pot0 po/xcsoar.pot # rename back-upped file to .pot          
          else
            # update real xcsoar.pot
            echo "Differences found, run normal update-po"
            - name: make working directory a safe commit dir again
              run: git config --global --add safe.directory /__w/XCSoar/XCSoar
            - name: Update pot files
              run: make update-po
            - name: Push Local Changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "Autocommit translation sources"
                file_pattern: "*.pot" # add ' *.po' after test runs finished
          fi
          rm po/xcsoar.pox # delete test file
