---
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'po/**'
      - 'data/**'
    
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-22.04
    container: debian:bookworm-slim
    permissions:
      contents: write  
    steps:
      - name: Install checkout dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git \
          ca-certificates rsync openssh-client
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./ide/provisioning/install-debian-packages.sh UPDATE
          ./ide/provisioning/install-debian-packages.sh BASE
      - name: make working directory a safe commit dir
        run: git config --global --add safe.directory /__w/XCSoar/XCSoar

      - name: Copy xcsoar.pot (1)
        run: |
          cp -v po/xcsoar.pot po/xcsoar.old         
          cd ./po/
          ls -l xcsoar.*
          
      - name: Update pot files (2)
        run: |
          make update-po
          cd ./po/
          ls -l xcsoar.*

      - name: remove timestamps (3)
        run: |
          cp -v po/xcsoar.pot po/xcsoar.ref # keep xcsoar.pot to push
          sed -i '/^"POT-Creation-Date:/d' po/xcsoar.ref # updated file
          sed -i '/^"POT-Creation-Date:/d' po/xcsoar.old # old file
          cd ./po/
          ls -l xcsoar.*
          
      - name: Check for differences (4)
        id: check_test
        run: |
          if diff --normal po/xcsoar.ref po/xcsoar.old; then
            echo "No differences found, no update"
          else
            echo "Differences found, push local changes"  
            echo "do-update=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Push Local Changes (5)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autocommit translation sources"
          file_pattern: "*.pot"
        if: do_update == 'true'
