---
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'po/**'
      - 'data/**'
    
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-22.04
    container: debian:bookworm-slim
    permissions:
      contents: write  
    steps:
      - name: Install checkout dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git \
          ca-certificates rsync openssh-client
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./ide/provisioning/install-debian-packages.sh UPDAT
          ./ide/provisioning/install-debian-packages.sh BASE
      - name: make working directory a safe commit dir
        run: git config --global --add safe.directory /__w/XCSoar/XCSoar

      - name: Backup existing file in po
        run: |
          mkdir -v -p ./tempo/
          cp -v po/xcsoar.pot tempo/xcsoar.px0 # backup
          cp -v po/xcsoar.pot tempo/xcsoar.px1 # old file to test
       
      - name: Update pot files
        run: make update-po
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autocommit translation sources"
          file_pattern: "*.pot"
          
      - name: copy new pot file and remove timestamps
        run: |
          cp -v po/xcsoar.pot tempo/xcsoar.px2 # new file to compare
          sed -i '/^"POT-Creation-Date:/d' tempo/xcsoar.px1 # old file
          sed -i '/^"POT-Creation-Date:/d' tempo/xcsoar.px2 # new file
      - name: Check for differences
        run: |
          if diff -q tempo/xcsoar.px1 tempo/xcsoar.px2; then
            echo "No difference found, restore backup file"
            rm -v po/xcsoar.pot # remove modified .pot
            cp -v tempo/xcsoar.px0 po/xcsoar.pot # copy backup files back to po-dir
          else
            echo "Differences found, keep new files in ./po/"
          fi
      - name: Clean-up
        run: |
          cd tempo/
          ls -l
          cd ./po/
          ls -l
      
     
        


