---
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'po/**'
      - 'data/**'
    
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-22.04
    container: debian:bookworm-slim
    permissions:
      contents: write  
    steps:
      - name: Install checkout dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git \
          ca-certificates rsync openssh-client
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./ide/provisioning/install-debian-packages.sh UPDAT
          ./ide/provisioning/install-debian-packages.sh BASE
      - name: make working directory a safe commit dir
        run: git config --global --add safe.directory /__w/XCSoar/XCSoar

      - name: duplicate existing file in po/
        run: |
          cp -v po/xcsoar.pot po/xcsoar_backup.px0 # original as backup
          cp -v po/xcsoar.pot po/xcsoar_reference.px1 # old file as reference
          cp -v po/xcsoar.pot po/xcsoar_test.pot # file to update for test
          cd ./po/
          ls -l xcsoar_*.* # to verify presence of files
          
      - name: Update pot file
        run: make update-po
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autocommit test file"
          file_pattern: "xcsoar_test.pot" 
          
      - name: remove timestamps
        run: |
          sed -i '/^"POT-Creation-Date:/d' po/xcsoar_test.pot # updated file
          sed -i '/^"POT-Creation-Date:/d' po/xcsoar_reference.px1 # ref file
          cd ./po/
          ls -l xcsoar_*.* # to verify presence of files
      - name: Check for differences
        run: |
          if diff --normal po/xcsoar_test.pot po/xcsoar_reference.px1; then
            echo "No difference found, keep original pot file"
            #rm -v po/xcsoar.pot
            #mv -v po/xcsoar_backup.px0 po/xcsoar.pot # use backup pot file
          else
            echo "Differences found, run real update-po"
            - name: Update pot files
              run: make update-po
            - name: Push Local Changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "Autocommit translation sources"
                file_pattern: "*.pot"
          fi
      - name: Clean-up
        run: |
          cd ./po/
          ls -l xcsoar_*.* # to verify presence of files
          # rm -v po/xcsoar_test.pot
          # rm -v po/xcsoar_reference.px1
            
